version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - echo "build step"
     #- aws s3 sync --delete . "s3://www.danielholloway.me/?region=us-east-2"
 post_build:
   commands:
     - echo "post_build step"
artifacts:
  files:
    - index.html
    - package.json
    - node_modules/*
    - images/